import math
sayi1 = float(input('Birinci sayıyı girin: '))
sayi2 = float(input('İkinci sayıyı girin: '))
sayi3 = float(input('Üçüncü sayıyı girin: '))
sayi4 = float(input('Dördüncü sayıyı girin: '))
sayi5 = float(input('Beşinci sayıyı girin: '))
karekok1=float(math.sqrt(sayi1))
karekok2=float(math.sqrt(sayi2))
karekok3=float(math.sqrt(sayi3))
karekok4=float(math.sqrt(sayi4))
karekok5=float(math.sqrt(sayi5))
print('Birinci sayinin karekökü '+str(karekok1))
print('İkinci sayinin karekökü '+str(karekok2))
print('Üçüncü sayinin karekökü '+str(karekok3))
print('Dördüncü sayinin karekökü '+str(karekok4))
print('Beşinci sayinin karekökü '+str(karekok5))